### ISSUE TITLE
hacktoberfest

### ISSUE THREAD

**Issue by whitebeard10** [whitebeard10/ArtVue#3]
There is a missing page for 
exclusives.php (<li><a href="#">Exclusives</a></li>)
in home.php
 you can contribute by adding the page relevant to the project theme in php folder (php/exclusives.php).
You can look at readme.md for cloning this repo

**Comment by mhdamaan79** [comment]
I would like to work on this issue. Please assign this issue to me.

**Comment by whitebeard10** [comment]
Hey, thanks for your interest in this project. I have assigned this issue to you.
