### ISSUE TITLE
Not redirecting to home page

### ISSUE THREAD

**Issue by ghost** [whitebeard10/ArtVue#5]
When I clicked on the "Get Started" Button, the home.php file started downloading

**Comment by whitebeard10** [comment]
Hi @Zaidsiddiqui1 , as this is a PHP project, you need to set a xampp server in your local machine to run it, for that , you need to download and install xampp, create and set the related databse and table,  start sql and apache server from xampp, put the project inside htdoc folder of xampp, an and  then run the project url starting with "http://localhost/project_name/index_file", please feel free to ask if in doubt further.
